<?php

/**
 * Implements hook_help().
 */
function curso_module_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.curso_module':
      return '<p> Este es el hook_help de nuestro modulo del curso. </p>';
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * @param \Drupal\node\NodeInterface $node
 */
function curso_module_node_update(\Drupal\node\NodeInterface $node) {
  dpm('Drupal llama a nuestro hook_ENTITY_TYPE_update');
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param \Drupal\node\NodeInterface $node
 */
function curso_module_node_insert(\Drupal\node\NodeInterface $node) {
  dpm('Drupal llama a nuestro hook_ENTITY_TYPE_insert');
}

/**
 * Implements hook_theme().
 */
function curso_module_theme($existing, $type, $theme, $path)
{
  return [
    'curso_plantilla' => [
      'variables' => [
        'etiqueta' => NULL,
        'tipo' => NULL,
      ]
    ]
  ];
}

/**
 * Implements hook_form_alter().
 */
function curso_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  switch ($form_id) {
    case 'curso_module_curso_form':
      $form['checkbox']['#required'] = FALSE;
      break;
    case 'node_article_form':
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function curso_module_form_curso_module_curso_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  $form['checkbox']['#required'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function curso_module_form_node_article_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
 t('This is the page of the form');
}
